docker_build(
  'alextsoh/client-react',  
  './',                    
  dockerfile='./Dockerfile.nginx' 
)
k8s_yaml('../k8s/client-react/Deployment.yaml')
k8s_resource('client-react-nginx', port_forwards=['8080:8080'])
